import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-zinc-900 bg-zinc-100`}>
        <div className="max-w-[1000px] 2xl:max-w-[1280px] min-[2000px]:max-w-[1600px] bg-white h-screen m-auto border-l border-r">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
